config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get 'help', to: 'static_pages#help'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'

  resources :channels do
    resource :channel_user
    resources :messages
  end

  devise_for :user
  resources :countries
  resources :states
  resources :municipalities
  resources :settlements
  resources :addresses
  resources :relationships
  resources :attendance_types
  resources :groups
  resources :evaluation_periods
  resources :turns
  resources :modalities
  resources :academic_cycles
  resources :cycle_types
  resources :courses
  resources :grades
  resources :syllabuses
  resources :careers
  resources :educative_levels
  resources :classrooms
  resources :buildings
  resources :campuses
  resources :institutions
  resources :statuses
  resources :currencies

  resources :homework_marks
  resources :student_homeworks
  resources :course_homeworks
  resources :student_courses
  resources :course_marks
  resources :evaluation_attendances
  resources :tutors
  resources :parents
  resources :students
  resources :course_evaluations
  resources :professors
  resources :campus_evaluations
  resources :turn_evaluations
  resources :cycle_turns
  resources :cycle_modalities
  resources :grade_courses
  resources :syllabus_grades
  resources :professor_courses
  resources :user_addresses
  resources :campus_addresses
  resources :institution_addresses
end

app/controllers/campus_addresses_controller.rb
# frozen_string_literal: true

class CampusAddressesController < ApplicationController
  before_action :set_campus_address, only: %i[show edit update destroy]

  # GET /campus_addresses
  # GET /campus_addresses.json
  def index
    @campus_addresses = CampusAddress.all
  end

  # GET /campus_addresses/1
  # GET /campus_addresses/1.json
  def show; end

  # GET /campus_addresses/new
  def new
    @campus_address = CampusAddress.new
  end

  # GET /campus_addresses/1/edit
  def edit; end

  # POST /campus_addresses
  # POST /campus_addresses.json
  def create
    @campus_address = CampusAddress.new(campus_address_params)

    respond_to do |format|
      if @campus_address.save
        format.html { redirect_to @campus_address, notice: 'Campus address was successfully created.' }
        format.json { render :show, status: :created, location: @campus_address }
      else
        format.html { render :new }
        format.json { render json: @campus_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campus_addresses/1
  # PATCH/PUT /campus_addresses/1.json
  def update
    respond_to do |format|
      if @campus_address.update(campus_address_params)
        format.html { redirect_to @campus_address, notice: 'Campus address was successfully updated.' }
        format.json { render :show, status: :ok, location: @campus_address }
      else
        format.html { render :edit }
        format.json { render json: @campus_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campus_addresses/1
  # DELETE /campus_addresses/1.json
  def destroy
    @campus_address.destroy
    respond_to do |format|
      format.html { redirect_to campus_addresses_url, notice: 'Campus address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_campus_address
    @campus_address = CampusAddress.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def campus_address_params
    params.require(:campus_address).permit(:campus_id, :address_id)
  end
end

app/helpers/campus_addresses_helper.rb
# frozen_string_literal: true

module CampusAddressesHelper
end

app/views/campus_addresses/_form.html.erb
<%= form_with(model: campus_address, local: true) do |form| %>
  <% if campus_address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(campus_address.errors.count, "error") %> prohibited this campus_address from being saved:</h2>

      <ul>
        <% campus_address.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :campus_id %>
    <%= form.text_field :campus_id %>
  </div>

  <div class="field">
    <%= form.label :address_id %>
    <%= form.text_field :address_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/campus_addresses/edit.html.erb
<h1>Editing Campus Address</h1>

<%= render 'form', campus_address: @campus_address %>

<%= link_to 'Show', @campus_address %> |
<%= link_to 'Back', campus_addresses_path %>

app/views/campus_addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Campus Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Campus</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campus_addresses.each do |campus_address| %>
      <tr>
        <td><%= campus_address.campus_id %></td>
        <td><%= campus_address.address_id %></td>
        <td><%= link_to 'Show', campus_address %></td>
        <td><%= link_to 'Edit', edit_campus_address_path(campus_address) %></td>
        <td><%= link_to 'Destroy', campus_address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Campus Address', new_campus_address_path %>

app/views/campus_addresses/new.html.erb
<h1>New Campus Address</h1>

<%= render 'form', campus_address: @campus_address %>

<%= link_to 'Back', campus_addresses_path %>

app/views/campus_addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Campus:</strong>
  <%= @campus_address.campus_id %>
</p>

<p>
  <strong>Address:</strong>
  <%= @campus_address.address_id %>
</p>

<%= link_to 'Edit', edit_campus_address_path(@campus_address) %> |
<%= link_to 'Back', campus_addresses_path %>