config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get 'help', to: 'static_pages#help'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'

  resources :channels do
    resource :channel_user
    resources :messages
  end

  devise_for :user
  resources :countries
  resources :states
  resources :municipalities
  resources :settlements
  resources :addresses
  resources :relationships
  resources :attendance_types
  resources :groups
  resources :evaluation_periods
  resources :turns
  resources :modalities
  resources :academic_cycles
  resources :cycle_types
  resources :courses
  resources :grades
  resources :syllabuses
  resources :careers
  resources :educative_levels
  resources :classrooms
  resources :buildings
  resources :campuses
  resources :institutions
  resources :statuses
  resources :currencies

  resources :homework_marks
  resources :student_homeworks
  resources :course_homeworks
  resources :student_courses
  resources :course_marks
  resources :evaluation_attendances
  resources :tutors
  resources :parents
  resources :students
  resources :course_evaluations
  resources :professors
  resources :campus_evaluations
  resources :turn_evaluations
  resources :cycle_turns
  resources :cycle_modalities
  resources :grade_courses
  resources :syllabus_grades
  resources :professor_courses
  resources :user_addresses
  resources :campus_addresses
  resources :institution_addresses
end

app/models/educative_level.rb
# frozen_string_literal: true

# Educative level model
class EducativeLevel < ApplicationRecord
  # Belongs to associations ---------------------------------------------------
  belongs_to :status

  # Has many associations -----------------------------------------------------
  has_many :careers, dependent: :restrict_with_error
  has_many :syllabuses, through: :careers
  has_many :grades, through: :careers
  has_many :courses, through: :careers

  # Validations ---------------------------------------------------------------
  validates :code, :name, presence: true
  validates :code, uniqueness: true, length: { minimum: 1, maximum: 16 }
  validates :name, length: { minimum: 1, maximum: 255 }
end

app/controllers/educative_levels_controller.rb
# frozen_string_literal: true

# Educative levels controller
class EducativeLevelsController < ApplicationController
  before_action :set_educative_level, only: %i[show edit update destroy]

  # GET /educative_levels
  # GET /educative_levels.json
  def index
    pagination = { page: params[:page], per_page: 20 }
    @educative_levels = EducativeLevel.paginate(pagination)
                                      .includes(:status)
  end

  # GET /educative_levels/1
  # GET /educative_levels/1.json
  def show; end

  # GET /educative_levels/new
  def new
    @educative_level = EducativeLevel.new
  end

  # GET /educative_levels/1/edit
  def edit; end

  # POST /educative_levels
  # POST /educative_levels.json
  def create
    @educative_level = EducativeLevel.new(educative_level_params)

    respond_to do |format|
      if @educative_level.save
        format.html { redirect_to @educative_level, notice: t('created_resource', resource: resource_name) }
        format.json { render :show, status: :created, location: @educative_level }
      else
        format.html { render :new }
        format.json { render json: @educative_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /educative_levels/1
  # PATCH/PUT /educative_levels/1.json
  def update
    respond_to do |format|
      if @educative_level.update(educative_level_params)
        format.html { redirect_to @educative_level, notice: t('updated_resource', resource: resource_name) }
        format.json { render :show, status: :ok, location: @educative_level }
      else
        format.html { render :edit }
        format.json { render json: @educative_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educative_levels/1
  # DELETE /educative_levels/1.json
  def destroy
    @educative_level.destroy
    respond_to do |format|
      format.html { redirect_to educative_levels_url, notice: t('destroyed_resource', resource: resource_name) }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_educative_level
    @educative_level = EducativeLevel.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def educative_level_params
    params.require(:educative_level).permit(:code, :name, :description, :status_id)
  end
end

app/helpers/educative_levels_helper.rb
# frozen_string_literal: true

module EducativeLevelsHelper
end

app/views/educative_levels/_form.html.erb
<%= form_with(model: educative_level, local: true) do |form| %>
  <%= render 'shared/error_messages', object: form.object %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :status_id %>
    <%= form.collection_select :status_id, Status.all, :id, :name, {},
                               class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary form-control' %>
  </div>
<% end %>

app/views/educative_levels/edit.html.erb
<% provide(:title, t('edit_resource', resource: t('activerecord.models.educative_level'))) %>
<% provide :card_title, t('activerecord.models.educative_level') %>

<%= render 'shared/cards/form_card' do %>
  <%= render 'form', educative_level: @educative_level %>
  <% content_for :card_footer do %>
    <%= link_to @educative_level, class: 'btn btn-sm btn-info' do %>
      <%= icon('fas', 'eye') %> <%= t('show') %>
    <% end %>
    <%= link_to educative_levels_path, class: 'btn btn-sm btn-danger' do %>
      <%= icon('fas', 'undo-alt') %> <%= t('back') %>
    <% end %>
  <% end %>
<% end %>

app/views/educative_levels/index.html.erb
<% provide(:title, t('educative_levels')) %>

<% content_for :card_header do %>
  <%= will_paginate @educative_levels, class: 'pagination-sm float-right',
                    :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
<% end %>

<% content_for :card_footer do %>
  <%= link_to new_educative_level_path, class: 'btn btn-sm btn-primary' do %>
    <%= icon('fas', 'plus-circle') %>
    <%= t('new_resource', resource: t('activerecord.models.educative_level')) %>
  <% end %>
  <%= will_paginate @educative_levels, class: 'pagination-sm m-0 float-right',
                    :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
<% end %>

<%= render 'shared/cards/index_card' do %>
  <table class="table table-hover table-head-fixed text-nowrap">
    <thead>
    <tr>
      <th><%= t('activerecord.attributes.educative_level.code') %></th>
      <th><%= t('activerecord.attributes.educative_level.name') %></th>
      <th><%= t('activerecord.attributes.educative_level.description') %></th>
      <th><%= t('activerecord.attributes.educative_level.status_id') %></th>
      <th colspan="1"></th>
    </tr>
    </thead>

    <tbody>
    <% @educative_levels.each do |educative_level| %>
      <tr>
        <td><%= educative_level.code %></td>
        <td><%= educative_level.name %></td>
        <td><%= educative_level.description %></td>
        <td><%= educative_level.status.name %></td>
        <td>
          <%= link_to educative_level, class: 'btn btn-sm btn-info' do %>
            <%= icon('fas', 'eye') %> <%= t('show') %>
          <% end %>
          <%= link_to edit_educative_level_path(educative_level), class: 'btn btn-sm btn-success' do %>
            <%= icon('fas', 'edit') %> <%= t('edit') %>
          <% end %>
          <%= link_to educative_level, method: :delete, data: { confirm: t('you_sure') }, class: 'btn btn-sm btn-danger' do %>
            <%= icon('fas', 'trash-alt') %> <%= t('destroy') %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/educative_levels/new.html.erb
<% provide(:title, t('new_resource', resource: t('activerecord.models.educative_level'))) %>
<% provide :card_title, t('activerecord.models.educative_level') %>

<%= render 'shared/cards/form_card' do %>
  <%= render 'form', educative_level: @educative_level %>
  <% content_for :card_footer do %>
    <%= link_to educative_levels_path, class: 'btn btn-sm btn-danger' do %>
      <%= icon('fas', 'undo-alt') %> <%= t('back') %>
    <% end %>
  <% end %>
<% end %>

app/views/educative_levels/show.html.erb
<% provide :title, @educative_level.name %>
<% provide :card_title, t('activerecord.models.educative_level') %>
<% content_for :card_footer do %>
  <%= link_to edit_educative_level_path(@educative_level), class: 'btn btn-sm btn-success' do %>
    <%= icon('fas', 'edit') %> <%= t('edit') %>
  <% end %>
  <%= link_to educative_levels_path, class: 'btn btn-sm btn-danger' do %>
    <%= icon('fas', 'undo-alt') %> <%= t('back') %>
  <% end %>
<% end %>

<%= render 'shared/cards/show' do %>
  <p>
    <strong><%= t('activerecord.attributes.educative_level.code') %>:</strong>
    <%= @educative_level.code %>
  </p>

  <p>
    <strong><%= t('activerecord.attributes.educative_level.name') %>:</strong>
    <%= @educative_level.name %>
  </p>

  <p>
    <strong><%= t('activerecord.attributes.educative_level.description') %>
      :</strong>
    <%= @educative_level.description %>
  </p>

  <p>
    <strong><%= t('activerecord.attributes.educative_level.status_id') %>
      :</strong>
    <%= @educative_level.status.name %>
  </p>
<% end %>