config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get 'help', to: 'static_pages#help'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'

  resources :channels do
    resource :channel_user
    resources :messages
  end

  devise_for :user
  resources :countries
  resources :states
  resources :municipalities
  resources :settlements
  resources :addresses
  resources :relationships
  resources :attendance_types
  resources :groups
  resources :evaluation_periods
  resources :turns
  resources :modalities
  resources :academic_cycles
  resources :cycle_types
  resources :courses
  resources :grades
  resources :syllabuses
  resources :careers
  resources :educative_levels
  resources :classrooms
  resources :buildings
  resources :campuses
  resources :institutions
  resources :statuses
  resources :currencies

  resources :homework_marks
  resources :student_homeworks
  resources :course_homeworks
  resources :student_courses
  resources :course_marks
  resources :evaluation_attendances
  resources :tutors
  resources :parents
  resources :students
  resources :course_evaluations
  resources :professors
  resources :campus_evaluations
  resources :turn_evaluations
  resources :cycle_turns
  resources :cycle_modalities
  resources :grade_courses
  resources :syllabus_grades
  resources :professor_courses
  resources :user_addresses
  resources :campus_addresses
  resources :institution_addresses
end

app/views/layouts/dashboards/_admin.html.erb
<div class="row">
  <div class="col-lg-3">
    <div class="small-box bg-gradient-info">
      <div class="inner">
        <h3><%= EducativeLevel.count %></h3>
        <p><%= t('educative_levels') %></p>
      </div>
      <div class="icon">
        <%= icon('fas', 'layer-group') %>
      </div>
      <%= link_to educative_levels_path, class: 'small-box-footer' do %>
        <%= t('more_info') %> <%= icon('fas', 'arrow-circle-right') %>
      <% end %>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="small-box bg-gradient-info">
      <div class="inner">
        <h3><%= Career.count %></h3>
        <p><%= t('careers') %></p>
      </div>
      <div class="icon">
        <%= icon('fas', 'graduation-cap') %>
      </div>
      <%= link_to careers_path, class: 'small-box-footer' do %>
        <%= t('more_info') %> <%= icon('fas', 'arrow-circle-right') %>
      <% end %>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="small-box bg-gradient-info">
      <div class="inner">
        <h3><%= Syllabus.count %></h3>
        <p><%= t('syllabuses') %></p>
      </div>
      <div class="icon">
        <%= icon('fas', 'list') %>
      </div>
      <%= link_to syllabuses_path, class: 'small-box-footer' do %>
        <%= t('more_info') %> <%= icon('fas', 'arrow-circle-right') %>
      <% end %>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="small-box bg-gradient-info">
      <div class="inner">
        <h3><%= Course.count %></h3>
        <p><%= t('courses') %></p>
      </div>
      <div class="icon">
        <%= icon('fas', 'book-open') %>
      </div>
      <%= link_to courses_path, class: 'small-box-footer' do %>
        <%= t('more_info') %> <%= icon('fas', 'arrow-circle-right') %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/dashboards/_parent.html.erb
<div class="row">
  <div class="col-lg-3">
    <div class="small-box bg-info">
      <div class="inner">
        <h3><%= t('courses') %></h3>
        <p><%= t('my_courses') %></p>
      </div>
      <div class="icon">
        <%= icon('fas', 'chalkboard-teacher') %>
      </div>
      <%= link_to '#', class: 'small-box-footer' do %>
        <%= t('more_info') %> <%= icon('fas', 'arrow-circle-right') %>
      <% end %>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="small-box bg-info">
      <div class="inner">
        <h3><%= t('courses') %></h3>
        <p><%= t('my_courses') %></p>
      </div>
      <div class="icon">
        <%= icon('fas', 'chalkboard-teacher') %>
      </div>
      <%= link_to '#', class: 'small-box-footer' do %>
        <%= t('more_info') %> <%= icon('fas', 'arrow-circle-right') %>
      <% end %>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="small-box bg-info">
      <div class="inner">
        <h3><%= t('courses') %></h3>
        <p><%= t('my_courses') %></p>
      </div>
      <div class="icon">
        <%= icon('fas', 'chalkboard-teacher') %>
      </div>
      <%= link_to '#', class: 'small-box-footer' do %>
        <%= t('more_info') %> <%= icon('fas', 'arrow-circle-right') %>
      <% end %>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="small-box bg-info">
      <div class="inner">
        <h3><%= t('courses') %></h3>
        <p><%= t('my_courses') %></p>
      </div>
      <div class="icon">
        <%= icon('fas', 'chalkboard-teacher') %>
      </div>
      <%= link_to '#', class: 'small-box-footer' do %>
        <%= t('more_info') %> <%= icon('fas', 'arrow-circle-right') %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/dashboards/_professor.html.erb
<div class="row">
  <div class="col-lg-3">
    <div class="small-box bg-gradient-info">
      <div class="inner">
        <h3><%= current_user.professor.professor_courses.count %></h3>
        <p><%= t('professor_courses') %></p>
      </div>
      <div class="icon">
        <%= icon('fas', 'book-reader') %>
      </div>
      <%= link_to professor_courses_path, class: 'small-box-footer' do %>
        <%= t('more_info') %> <%= icon('fas', 'arrow-circle-right') %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/dashboards/_student.html.erb
<div class="row">
  <div class="col-lg-3">
    <div class="small-box bg-gradient-info">
      <div class="inner">
        <h3><%= current_user.student.student_courses.count %></h3>
        <p><%= t('student_courses') %></p>
      </div>
      <div class="icon">
        <%= icon('fas', 'school') %>
      </div>
      <%= link_to student_courses_path, class: 'small-box-footer' do %>
        <%= t('more_info') %> <%= icon('fas', 'arrow-circle-right') %>
      <% end %>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="small-box bg-gradient-info">
      <div class="inner">
        <h3><%= current_user.student.student_homeworks.count %></h3>
        <p><%= t('student_homeworks') %></p>
      </div>
      <div class="icon">
        <%= icon('fas', 'building') %>
      </div>
      <%= link_to student_homeworks_path, class: 'small-box-footer' do %>
        <%= t('more_info') %> <%= icon('fas', 'arrow-circle-right') %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/dashboards/_super_admin.html.erb
<div class="row">
  <div class="col-lg-3">
    <div class="small-box bg-gradient-info">
      <div class="inner">
        <h3><%= Institution.count %></h3>
        <p><%= t('institutions') %></p>
      </div>
      <div class="icon">
        <%= icon('fas', 'school') %>
      </div>
      <%= link_to institutions_path, class: 'small-box-footer' do %>
        <%= t('more_info') %> <%= icon('fas', 'arrow-circle-right') %>
      <% end %>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="small-box bg-gradient-info">
      <div class="inner">
        <h3><%= Campus.count %></h3>
        <p><%= t('campuses') %></p>
      </div>
      <div class="icon">
        <%= icon('fas', 'building') %>
      </div>
      <%= link_to campuses_path, class: 'small-box-footer' do %>
        <%= t('more_info') %> <%= icon('fas', 'arrow-circle-right') %>
      <% end %>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="small-box bg-gradient-info">
      <div class="inner">
        <h3><%= Student.count %></h3>
        <p><%= t('students') %></p>
      </div>
      <div class="icon">
        <%= icon('fas', 'user-graduate') %>
      </div>
      <%= link_to students_path, class: 'small-box-footer' do %>
        <%= t('more_info') %> <%= icon('fas', 'arrow-circle-right') %>
      <% end %>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="small-box bg-gradient-info">
      <div class="inner">
        <h3><%= Professor.count %></h3>
        <p><%= t('professors') %></p>
      </div>
      <div class="icon">
        <%= icon('fas', 'user-tie') %>
      </div>
      <%= link_to professors_path, class: 'small-box-footer' do %>
        <%= t('more_info') %> <%= icon('fas', 'arrow-circle-right') %>
      <% end %>
    </div>
  </div>
</div>