config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get 'help', to: 'static_pages#help'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'

  resources :channels do
    resource :channel_user
    resources :messages
  end

  devise_for :user
  resources :countries
  resources :states
  resources :municipalities
  resources :settlements
  resources :addresses
  resources :relationships
  resources :attendance_types
  resources :groups
  resources :evaluation_periods
  resources :turns
  resources :modalities
  resources :academic_cycles
  resources :cycle_types
  resources :courses
  resources :grades
  resources :syllabuses
  resources :careers
  resources :educative_levels
  resources :classrooms
  resources :buildings
  resources :campuses
  resources :institutions
  resources :statuses
  resources :currencies

  resources :homework_marks
  resources :student_homeworks
  resources :course_homeworks
  resources :student_courses
  resources :course_marks
  resources :evaluation_attendances
  resources :tutors
  resources :parents
  resources :students
  resources :course_evaluations
  resources :professors
  resources :campus_evaluations
  resources :turn_evaluations
  resources :cycle_turns
  resources :cycle_modalities
  resources :grade_courses
  resources :syllabus_grades
  resources :professor_courses
  resources :user_addresses
  resources :campus_addresses
  resources :institution_addresses
end

app/models/evaluation_attendance.rb
# frozen_string_literal: true

# Evaluation attendance model
class EvaluationAttendance < ApplicationRecord
  # Belongs to associations ---------------------------------------------------
  belongs_to :course_evaluation
  belongs_to :attendance_type

  # Validations ---------------------------------------------------------------
  validates :student_course_id, uniqueness: { scope: %i[attendance_type_id date] }
end

app/controllers/evaluation_attendances_controller.rb
# frozen_string_literal: true

# Evaluation attendances controller
class EvaluationAttendancesController < ApplicationController
  before_action :set_evaluation_attendance, only: %i[show edit update destroy]

  # GET /evaluation_attendances
  # GET /evaluation_attendances.json
  def index
    pagination = { page: params[:page], per_page: 20 }
    @evaluation_attendances = EvaluationAttendance.paginate(pagination)
                                                  .includes(index_includes)
  end

  # GET /evaluation_attendances/1
  # GET /evaluation_attendances/1.json
  def show; end

  # GET /evaluation_attendances/new
  def new
    @evaluation_attendance = EvaluationAttendance.new
  end

  # GET /evaluation_attendances/1/edit
  def edit; end

  # POST /evaluation_attendances
  # POST /evaluation_attendances.json
  def create
    @evaluation_attendance = EvaluationAttendance.new(evaluation_attendance_params)

    respond_to do |format|
      if @evaluation_attendance.save
        format.html { redirect_to @evaluation_attendance, notice: t('created_resource', resource: resource_name) }
        format.json { render :show, status: :created, location: @evaluation_attendance }
      else
        format.html { render :new }
        format.json { render json: @evaluation_attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluation_attendances/1
  # PATCH/PUT /evaluation_attendances/1.json
  def update
    respond_to do |format|
      if @evaluation_attendance.update(evaluation_attendance_params)
        format.html { redirect_to @evaluation_attendance, notice: t('updated_resource', resource: resource_name) }
        format.json { render :show, status: :ok, location: @evaluation_attendance }
      else
        format.html { render :edit }
        format.json { render json: @evaluation_attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluation_attendances/1
  # DELETE /evaluation_attendances/1.json
  def destroy
    @evaluation_attendance.destroy
    respond_to do |format|
      format.html { redirect_to evaluation_attendances_url, notice: t('destroyed_resource', resource: resource_name) }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_evaluation_attendance
    @evaluation_attendance = EvaluationAttendance.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def evaluation_attendance_params
    params.require(:evaluation_attendance).permit(:student_id, :course_evaluation_id, :attendance_type_id, :date)
  end

  def index_includes
    [{ student_course:
           [{ course_evaluation:
                  [{ grade_course:
                         [{ syllabus_grade: %i[syllabus grade] }, :course] },
                   { campus_evaluation:
                         [{ turn_evaluation:
                                [{ cycle_turn:
                                       [{ cycle_modality:
                                              %i[academic_cycle modality] },
                                        :turn] },
                                 :evaluation_period] },
                          :campus] }, { professor: :user }, :group] },
            { student: :user }] },
     :attendance_type]
  end
end

app/helpers/evaluation_attendances_helper.rb
# frozen_string_literal: true

module EvaluationAttendancesHelper
end

app/views/evaluation_attendances/_form.html.erb
<%= form_with(model: evaluation_attendance, local: true) do |form| %>
  <%= render 'shared/error_messages', object: form.object %>

  <div class="field">
    <%= form.label :student_course_id %>
    <%= form.collection_select :student_course_id_id, StudentCourse.all,
                               :id, :name, {}, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :attendance_type_id %>
    <%= form.collection_select :attendance_type_id, AttendanceType.all,
                               :id, :name, {}, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, {}, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary form-control' %>
  </div>
<% end %>

app/views/evaluation_attendances/edit.html.erb
<% provide(:title, t('edit_resource', resource: t('activerecord.models.evaluation_attendance'))) %>
<% provide :card_title, t('activerecord.models.evaluation_attendance') %>

<%= render 'shared/cards/form_card' do %>
  <%= render 'form', evaluation_attendance: @evaluation_attendance %>
  <% content_for :card_footer do %>
    <%= link_to @evaluation_attendance, class: 'btn btn-sm btn-info' do %>
      <%= icon('fas', 'eye') %> <%= t('show') %>
    <% end %>
    <%= link_to evaluation_attendances_path, class: 'btn btn-sm btn-danger' do %>
      <%= icon('fas', 'undo-alt') %> <%= t('back') %>
    <% end %>
  <% end %>
<% end %>

app/views/evaluation_attendances/index.html.erb
<% provide(:title, t('evaluation_attendances')) %>

<% content_for :card_header do %>
  <%= will_paginate @evaluation_attendances, class: 'pagination-sm float-right',
                    :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
<% end %>

<% content_for :card_footer do %>
  <%= link_to new_evaluation_attendance_path, class: 'btn btn-sm btn-primary' do %>
    <%= icon('fas', 'plus-circle') %>
    <%= t('new_resource', resource: t('activerecord.models.evaluation_attendance')) %>
  <% end %>
  <%= will_paginate @evaluation_attendances, class: 'pagination-sm m-0 float-right',
                    :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
<% end %>

<%= render 'shared/cards/index_card' do %>
  <table class="table table-hover table-head-fixed text-nowrap">
    <thead>
    <tr>
      <th>
        <%= t('activerecord.attributes.evaluation_attendance.student_course_id') %></th>
      <th>
        <%= t('activerecord.attributes.evaluation_attendance.attendance_type_id') %></th>
      <th>
        <%= t('activerecord.attributes.evaluation_attendance.date') %></th>
      <th colspan="1"></th>
    </tr>
    </thead>

    <tbody>
    <% @evaluation_attendances.each do |evaluation_attendance| %>
      <tr>
        <td><%= evaluation_attendance.student_course.name %></td>
        <td><%= evaluation_attendance.attendance_type.name %></td>
        <td><%= evaluation_attendance.date %></td>
        <td>
          <%= link_to evaluation_attendance, class: 'btn btn-sm btn-info' do %>
            <%= icon('fas', 'eye') %> <%= t('show') %>
          <% end %>
          <%= link_to edit_evaluation_attendance_path(evaluation_attendance), class: 'btn btn-sm btn-success' do %>
            <%= icon('fas', 'edit') %> <%= t('edit') %>
          <% end %>
          <%= link_to evaluation_attendance, method: :delete, data: { confirm: t('you_sure') }, class: 'btn btn-sm btn-danger' do %>
            <%= icon('fas', 'trash-alt') %> <%= t('destroy') %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/evaluation_attendances/new.html.erb
<% provide(:title, t('new_resource', resource: t('activerecord.models.evaluation_attendance'))) %>
<% provide :card_title, t('activerecord.models.evaluation_attendance') %>

<%= render 'shared/cards/form_card' do %>
  <%= render 'form', evaluation_attendance: @evaluation_attendance %>
  <% content_for :card_footer do %>
    <%= link_to evaluation_attendances_path, class: 'btn btn-sm btn-danger' do %>
      <%= icon('fas', 'undo-alt') %> <%= t('back') %>
    <% end %>
  <% end %>
<% end %>

app/views/evaluation_attendances/show.html.erb
<% provide :title, @evaluation_attendance.name %>
<% provide :card_title, t('activerecord.models.evaluation_attendance') %>
<% content_for :card_footer do %>
  <%= link_to edit_evaluation_attendance_path(@evaluation_attendance), class: 'btn btn-sm btn-success' do %>
    <%= icon('fas', 'edit') %> <%= t('edit') %>
  <% end %>
  <%= link_to evaluation_attendances_path, class: 'btn btn-sm btn-danger' do %>
    <%= icon('fas', 'undo-alt') %> <%= t('back') %>
  <% end %>
<% end %>

<%= render 'shared/cards/show' do %>
  <p>
    <strong>
      <%= t('activerecord.attributes.evaluation_attendance.student_course_id') %>
      :</strong>
    <%= @evaluation_attendance.student_course.name %>
  </p>

  <p>
    <strong>
      <%= t('activerecord.attributes.evaluation_attendance.attendance_type_id') %>
      :</strong>
    <%= @evaluation_attendance.attendance_type.name %>
  </p>

  <p>
    <strong>
      <%= t('activerecord.attributes.evaluation_attendance.date') %>:</strong>
    <%= @evaluation_attendance.date %>
  </p>
<% end %>